!MESSAGE LIB is $(LIB)
all:
	@echo Printing a message:
	@echo Hello, this is an nmake echo example!
	@echo Displaying LIB environment variable:
	@echo $(LIB)

clean:
	@echo Nothing to clean.

.PHONY: all clean